name: Docker Pre Setup
description: "Setup the Environment for Docker"
inputs:
  registry:
    description: "Docker Registry"
    required: false
    default: "ghcr.io"
  username:
    description: "GitHub Username"
    required: true
  gh-token:
    description: "GitHub Token"
    required: true
  image-name:
    description: "Docker Image Name"
    required: true
outputs:
  labels:
    description: "Docker Image Labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: "composite"
  steps:
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.gh-token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ inputs.registry }}/${{ inputs.image-name }}